[package]
name = "avila-id"
version = "0.1.0"
edition = "2021"
authors = ["Nícolas Ávila <nicolas@avila.inc>"]
license = "MIT OR Apache-2.0"
description = "AVL Platform unique ID generator - replacement for uuid"
repository = "https://github.com/avilaops/arxis"
homepage = "https://avila.inc"
keywords = ["id", "uuid", "avila", "avl"]

[dependencies]
# Zero dependências - Rust std apenas

[lib]
name = "avila_id"
path = "src/lib.rs"
